### ISSUE TITLE
A minor problem with the built-in Dark theme

### ISSUE THREAD

**Issue by chadchoi** [e3kskoy7wqk/Firefox-for-windows-7#12]
The items on `Time range to clear` list in `Clear recent history...` are invisible. Only the default selected item is visible. The rest are not. But you can somewhat see them when you hover the mouse over them. There is no such problem on r3dfox.

p/s: White text on white background? When you hover the mouse over the item, the background is dimmed a bit so you can somewhat see the white text?

**Comment by e3kskoy7wqk** [comment]
Hello, I've made some modifications to address the issue, and the new version is currently being built. You should see it available soon.

**Comment by e3kskoy7wqk** [comment]
The Firefox user interface seems to be written in HTML, but I have no knowledge of HTML, CSS, JS, or even Rust. The only languages I'm familiar with are C and C++. Therefore, addressing user interface issues is quite challenging for me, and I'm unsure whether I've fundamentally resolved the problem or if my solution is optimal. Thus, I've documented my process and thoughts in solving this issue, hoping that more experienced individuals can provide feedback and corrections.

The following steps assume the Firefox source code version is 671d010bef89f043926f07e70bc3e4b09e89b171 and that my patch from commit 2cacd000366dc775b32ae11623f95b2a2140dd5b has been applied.

The issue occurs with the menupopup in browser/base/content/sanitize_v2.xhtml. Its background color does not change with the theme color, meaning that even if I apply the Dark theme, the menupopup background remains white.

Initially, I found that removing the following code block from toolkit\themes\shared\popup.css resolves the issue. However, this also causes the native menus in Firefox on Windows 7 to change color with the theme, which is undesirable.

```css
@media not (-moz-windows-non-native-menus) {
  menupopup {
    appearance: auto;
    -moz-default-appearance: menupopup;

    /* Native menus are always light */
    color-scheme: light !important;

    /* We set the background-color / border here so that it doesn't interfere with native styling. */
    background-color: Menu;
    border: 1px solid ThreeDShadow;
    --panel-background: transparent;
    --panel-border-color: transparent;
    --nested-margin: -3px;
    --panel-shadow-margin: 0px;
  }
}
```

Additionally, I noticed that the menupopup in other dialogs, such as browser/components/preferences/dialogs/fonts.xhtml, does not exhibit the same problem. I suspected that sanitize_v2.xhtml might be missing some global flags, causing its menupopup to be identified as a native menu. I compared sanitize_v2.xhtml and fonts.xhtml to find these flags, but the results were disappointing. They contained almost identical CSS, making it difficult to determine the cause of the issue in sanitize_v2.xhtml. Since I'm not proficient in JS, I couldn't determine if the menupopup style was being set in JS. I also examined the r3dfox source code but couldn't identify why r3dfox doesn't have this problem.

As a last resort, I used a rather crude method: setting the color-scheme for menupopup in browser/themes/windows/sanitizeDialog.css. This approach resolves the issue and hasn't shown any other adverse effects so far.

However, I firmly believe that I haven't fundamentally resolved the problem. At the very least, I can't explain why the menupopup styles differ between fonts.xhtml and sanitize_v2.xhtml. Therefore, I hope that more experienced individuals can provide a more comprehensive solution.
