### ISSUE TITLE
Bug Firefox 136: Firefox opens without a bar (close, minimize and minimize)

### ISSUE THREAD

**Issue by MrDick004** [e3kskoy7wqk/Firefox-for-windows-7#8]
![Image](https://github.com/user-attachments/assets/2242be1e-8422-4e05-b307-4c505f697b72)

The bug mainly happens when changing any language pack, I don't know if it is due to incompatibility by firefox for the language pack, but when in doubt I report this.

**Comment by e3kskoy7wqk** [comment]
Hello, this issue might be caused by Firefox theme packs. You can try resolving it by uninstalling or disabling all theme packs in Firefox.
The problem occurs because Firefox changes the color of the title bar when applying a theme, which works fine in Windows 10 and 11 but causes the title bar buttons to be obscured in Windows 7. I am currently working on a fix for this issue.

**Comment by MrDick004** [comment]
![Image](https://github.com/user-attachments/assets/fbb0d1c7-0ff8-4bae-b140-56906f85d409)

For the moment I solved it by taking the “browser” folder from a modified version of Firefox 134 for Windows 7, I took this “browser” folder and pasted it into the firefox 136 folder. This solution is not quite perfect as the windows 7 aero margin at the top for example is not showing, but at least now I can see the window close buttons etc, in case I attach the folder below if it helps you to understand what to change.

[browser.zip](https://github.com/user-attachments/files/18574815/browser.zip)

**Comment by e3kskoy7wqk** [comment]
Thank you very much for your help! After investigating for the past two days, I've found that this issue is quite challenging to resolve because it behaves differently on various devices.

I tested Firefox for Windows 7 on both a Windows 7 virtual machine and a physical Windows 7 machine. On the Windows 7 virtual machine, everything worked fine, and the title bar buttons displayed correctly regardless of the circumstances. However, on the physical Windows 7 machine, the title bar buttons sometimes did not display correctly, especially when themes that change the title bar color were applied (such as `Activist – Balanced` and `Firefox Alpenglow`). Interestingly, I noticed that [r3dfox](https://github.com/Eclipse-Community/r3dfox) also has this issue.

After attempting various solutions, I haven't been able to completely resolve the problem. However, I've fixed several errors from previous versions, which has allowed Firefox's built-in `Dark`, `Light`, and `System theme — auto` themes to display correctly on both my Windows 7 virtual machine and physical Windows 7 machine.

You can try the new version to see if the title bar buttons display correctly. I will continue to work on a complete solution to this issue.

Known issues with the new version include:
- When maximized, part of the title bar buttons may appear off-screen.
- When DWM is disabled, the title bar color may be incorrect, and menus may not display properly.
- Private Browsing may also cause the title bar buttons to be invisible.

If you encounter any other problems with Firefox for Windows 7, please let me know. Thank you once again!

**Comment by chadchoi** [comment]
I have used the Catsxp browser for a while. It also has problems with the title bar and tab bar on my Windows 8.1, even more annoying than Firefox-for-windows-7. If you have too many tabs opened, the tabs will go past the min-max-close button and everything is uncontrollable. Catsxp is also more crashy. I think the window management code of it is very buggy. I have never had even a single crash with Firefox-for-windows-7.

**Comment by e3kskoy7wqk** [comment]
Yes, that's because Chromium (Catsxp) relies heavily on C++ for its appearance, whereas Firefox relies more on HTML and CSS, which are less likely to cause crashes.

**Comment by e3kskoy7wqk** [comment]
In my reworked version, I seem to have completely resolved this issue. The browser does not exhibit the problem of the close, minimize, and maximize buttons being covered on my Windows 7 physical machine, Windows 7 virtual machine, and Windows 8.1 physical machine.

https://github.com/e3kskoy7wqk/Firefox-for-windows-7/releases/tag/rework

**Comment by ZepopaOwleMukasa** [comment]
@MrDick004 

Have you checked the latest builds as mentioned by the developers comment above? If so, is this issue resolved on your end? Don't forget to close your issue if that is indeed the case.

**Comment by aubymori** [comment]
@e3kskoy7wqk Sorry for bothering you, but do you mind pointing me to exactly how you fixed this? It's hard to track down since every release has its own patch files, so it would be greatly appreciated if you could isolate the fix for this issue so that I can fix it in my own fork.

**Comment by e3kskoy7wqk** [comment]
@aubymori I’d be happy to share my approach to resolving this issue.

The reason the Windows control buttons were being obscured is due to a bug in WebRender on Windows 7/8. However, instead of directly fixing the bug, Firefox worked around it by setting background properties on `:root` instead of `#navigator-toolbox` on Windows 7/8:

```css
/* TODO bug 1695280: Remove these media selectors and merge the rule below
   with the ruleset above. We must set background properties on :root and not
   #navigator-toolbox on Windows 7/8 due to a WebRender bug that hides the
   minimize/maximize/close buttons. */
@media not (-moz-platform: windows-win7) {
  @media not (-moz-platform: windows-win8) {
    #navigator-toolbox:-moz-lwtheme {
      background-color: var(--lwt-accent-color);
    }

    /* When a theme defines both theme_frame and additional_backgrounds, show
       the latter atop the former. */
   :root[lwtheme-image] #navigator-toolbox {
     background-image: var(--lwt-header-image), var(--lwt-additional-images);
     background-repeat: no-repeat, var(--lwt-background-tiling);
     background-position: right top, var(--lwt-background-alignment);
   }

   #navigator-toolbox:-moz-window-inactive:-moz-lwtheme {
     background-color: var(--lwt-accent-color-inactive, var(--lwt-accent-color));
   }
  }
}
/* TODO bug 1695280: Remove this block. */
@media (-moz-platform: windows-win7),
       (-moz-platform: windows-win8) {
  :root:-moz-lwtheme {
    background-color: var(--lwt-accent-color);
    background-image: var(--lwt-additional-images);
    background-repeat: var(--lwt-background-tiling);
    background-position: var(--lwt-background-alignment);
  }

  :root[lwtheme-image] {
    background-image: var(--lwt-header-image, linear-gradient(transparent, transparent)),  var(--lwt-additional-images) !important;
    background-repeat: no-repeat, var(--lwt-background-tiling);
    background-position: right top, var(--lwt-background-alignment) !important;
  }

  :root:-moz-lwtheme:-moz-window-inactive {
    background-color: var(--lwt-accent-color-inactive, var(--lwt-accent-color));
  }
}
```

The above code provides a workaround for the issue (although it has since been removed in https://github.com/mozilla/gecko-dev/commit/7e60f84b6ec7c303e07f303a4838e907265a9a05). Therefore, to address this issue, we simply need to follow the same approach and make the necessary modifications.

For example:
https://github.com/e3kskoy7wqk/Firefox-for-windows-7/blob/9461d2d231b66ef29ebf1f22978433261e52c9bd/2025-03-04.8d67fee56f0e8d736369bd7c970da61950a011be/7e60f84b6ec7c303e07f303a4838e907265a9a05.diff#L1995-L2015
https://github.com/e3kskoy7wqk/Firefox-for-windows-7/blob/9461d2d231b66ef29ebf1f22978433261e52c9bd/2025-03-04.8d67fee56f0e8d736369bd7c970da61950a011be/7e60f84b6ec7c303e07f303a4838e907265a9a05.diff#L2261-L2275
https://github.com/e3kskoy7wqk/Firefox-for-windows-7/blob/9461d2d231b66ef29ebf1f22978433261e52c9bd/2025-03-04.8d67fee56f0e8d736369bd7c970da61950a011be/7e60f84b6ec7c303e07f303a4838e907265a9a05.diff#L2287-L2294
https://github.com/e3kskoy7wqk/Firefox-for-windows-7/blob/9461d2d231b66ef29ebf1f22978433261e52c9bd/2025-03-04.8d67fee56f0e8d736369bd7c970da61950a011be/7e60f84b6ec7c303e07f303a4838e907265a9a05.diff#L2296-L2306
https://github.com/e3kskoy7wqk/Firefox-for-windows-7/blob/9461d2d231b66ef29ebf1f22978433261e52c9bd/2025-03-04.8d67fee56f0e8d736369bd7c970da61950a011be/7e60f84b6ec7c303e07f303a4838e907265a9a05.diff#L2313-L2321
https://github.com/e3kskoy7wqk/Firefox-for-windows-7/blob/9461d2d231b66ef29ebf1f22978433261e52c9bd/2025-03-04.8d67fee56f0e8d736369bd7c970da61950a011be/7e60f84b6ec7c303e07f303a4838e907265a9a05.diff#L2327-L2337
https://github.com/e3kskoy7wqk/Firefox-for-windows-7/blob/9461d2d231b66ef29ebf1f22978433261e52c9bd/2025-03-04.8d67fee56f0e8d736369bd7c970da61950a011be/7e60f84b6ec7c303e07f303a4838e907265a9a05.diff#L2340-L2345
https://github.com/e3kskoy7wqk/Firefox-for-windows-7/blob/9461d2d231b66ef29ebf1f22978433261e52c9bd/2025-03-04.8d67fee56f0e8d736369bd7c970da61950a011be/7e60f84b6ec7c303e07f303a4838e907265a9a05.diff#L2784-L2791

This should resolve the issue. If it doesn’t, you will need to revert https://github.com/mozilla/gecko-dev/commit/c8b1cc5de2b0e6fb5d3e65f8e033c7f33f7322b8 and any subsequent related changes. This is because https://github.com/mozilla/gecko-dev/commit/c8b1cc5de2b0e6fb5d3e65f8e033c7f33f7322b8 altered the execution logic of WebRender, which further exacerbated the problem. Unfortunately, I don’t have a better solution for this at the moment.

@K4sum1 I hope this information proves useful to you as well.
